name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2.11.0=py_0
  - dask-core=2.11.0=py_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - pandas=1.0.1=py37h0573a6f_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.10.0=py_0
